/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uf1pacdesarrollo;

/**
 *
 * @author POCAR
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /*metodo con switch case que según el botón de operación que se pulse
    realiza la operación*/
    public void operacion() {

        switch (calculo) {

            /*recoge el String que se ha escrito en el jTextField1, lo parsea
            a Double realiza la operación marcada. Lo asigna a la variable
            respuesta y se muestra en la pantalla. En el caso de que respuesta 
            tenga más de 14 decimales, lo redondea para que quepa en pantalla*/
            case 1: //suma
                respuesta = numero + Double.parseDouble(jTextField1.getText());
                jLabel1.setText(textoOperacion + jTextField1.getText());
                respuesta = Math.round(respuesta * Math.pow(10, 14)) / Math.pow(10, 14);
                jTextField1.setText(Double.toString(respuesta));
                puntoDecimal = 0;
                primerNumero = 0;
                break;

            case 2: //resta
                respuesta = numero - Double.parseDouble(jTextField1.getText());
                jLabel1.setText(textoOperacion + jTextField1.getText());
                respuesta = Math.round(respuesta * Math.pow(10, 14)) / Math.pow(10, 14);
                jTextField1.setText(Double.toString(respuesta));
                puntoDecimal = 0;
                primerNumero = 0;
                break;

            case 3: //multiplicación
                respuesta = numero * Double.parseDouble(jTextField1.getText());
                jLabel1.setText(textoOperacion + jTextField1.getText());
                respuesta = Math.round(respuesta * Math.pow(10, 14)) / Math.pow(10, 14);
                jTextField1.setText(Double.toString(respuesta));
                puntoDecimal = 0;
                primerNumero = 0;
                break;

            case 4: //división
                if (Double.parseDouble(jTextField1.getText()) == 0) {
                    jLabel1.setText("No puedes dividir por 0");
                } else {
                    respuesta = numero / Double.parseDouble(jTextField1.getText());
                }
                jLabel1.setText(textoOperacion + jTextField1.getText());
                respuesta = Math.round(respuesta * Math.pow(10, 14)) / Math.pow(10, 14);
                jTextField1.setText(Double.toString(respuesta));
                puntoDecimal = 0;
                primerNumero = 0;
                break;

            case 5: //elevado al cuadrado
                respuesta = Math.pow(numero, 2);
                jLabel1.setText(textoOperacion + " ^2 =");
                respuesta = Math.round(respuesta * Math.pow(10, 14)) / Math.pow(10, 14);
                jTextField1.setText(Double.toString(respuesta));
                puntoDecimal = 0;

                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCuadrado2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jBCuadrado1 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        JBDividir = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        jBMultiplicar = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jBRestar = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        jBSumar = new javax.swing.JButton();
        jBIgual = new javax.swing.JButton();
        JB0 = new javax.swing.JButton();
        jBComa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jBCuadrado2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBCuadrado2.setText("x^2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setLocation(new java.awt.Point(500, 300));
        setPreferredSize(new java.awt.Dimension(350, 450));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jBCuadrado1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBCuadrado1.setText("x^2");
        jBCuadrado1.setMaximumSize(new java.awt.Dimension(70, 50));
        jBCuadrado1.setMinimumSize(new java.awt.Dimension(70, 50));
        jBCuadrado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCuadrado1ActionPerformed(evt);
            }
        });

        jB7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jB7.setText("7");
        jB7.setMaximumSize(new java.awt.Dimension(70, 50));
        jB7.setMinimumSize(new java.awt.Dimension(70, 50));
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jBEliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBEliminar.setText("C");
        jBEliminar.setMaximumSize(new java.awt.Dimension(70, 50));
        jBEliminar.setMinimumSize(new java.awt.Dimension(70, 50));
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        JBDividir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JBDividir.setText("/");
        JBDividir.setMaximumSize(new java.awt.Dimension(70, 50));
        JBDividir.setMinimumSize(new java.awt.Dimension(70, 50));
        JBDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDividirActionPerformed(evt);
            }
        });

        JB9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JB9.setText("9");
        JB9.setMaximumSize(new java.awt.Dimension(70, 50));
        JB9.setMinimumSize(new java.awt.Dimension(70, 50));
        JB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB9ActionPerformed(evt);
            }
        });

        JB8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JB8.setText("8");
        JB8.setMaximumSize(new java.awt.Dimension(70, 50));
        JB8.setMinimumSize(new java.awt.Dimension(70, 50));
        JB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB8ActionPerformed(evt);
            }
        });

        jBBorrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBBorrar.setText("<--");
        jBBorrar.setMaximumSize(new java.awt.Dimension(70, 50));
        jBBorrar.setMinimumSize(new java.awt.Dimension(70, 50));
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        JB4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JB4.setText("4");
        JB4.setMaximumSize(new java.awt.Dimension(70, 50));
        JB4.setMinimumSize(new java.awt.Dimension(70, 50));
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });

        jBMultiplicar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBMultiplicar.setText("x");
        jBMultiplicar.setMaximumSize(new java.awt.Dimension(70, 50));
        jBMultiplicar.setMinimumSize(new java.awt.Dimension(70, 50));
        jBMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicarActionPerformed(evt);
            }
        });

        JB5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JB5.setText("5");
        JB5.setMaximumSize(new java.awt.Dimension(70, 50));
        JB5.setMinimumSize(new java.awt.Dimension(70, 50));
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });

        JB6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JB6.setText("6");
        JB6.setMaximumSize(new java.awt.Dimension(70, 50));
        JB6.setMinimumSize(new java.awt.Dimension(70, 50));
        JB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB6ActionPerformed(evt);
            }
        });

        jB1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jB1.setText("1");
        jB1.setMaximumSize(new java.awt.Dimension(70, 50));
        jB1.setMinimumSize(new java.awt.Dimension(70, 50));
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jBRestar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBRestar.setText("-");
        jBRestar.setMaximumSize(new java.awt.Dimension(70, 50));
        jBRestar.setMinimumSize(new java.awt.Dimension(70, 50));
        jBRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRestarActionPerformed(evt);
            }
        });

        jB2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jB2.setText("2");
        jB2.setMaximumSize(new java.awt.Dimension(70, 50));
        jB2.setMinimumSize(new java.awt.Dimension(70, 50));
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        JB3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JB3.setText("3");
        JB3.setMaximumSize(new java.awt.Dimension(70, 50));
        JB3.setMinimumSize(new java.awt.Dimension(70, 50));
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        jBSumar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBSumar.setText("+");
        jBSumar.setMaximumSize(new java.awt.Dimension(70, 50));
        jBSumar.setMinimumSize(new java.awt.Dimension(70, 50));
        jBSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSumarActionPerformed(evt);
            }
        });

        jBIgual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBIgual.setText("=");
        jBIgual.setMaximumSize(new java.awt.Dimension(70, 50));
        jBIgual.setMinimumSize(new java.awt.Dimension(70, 50));
        jBIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIgualActionPerformed(evt);
            }
        });

        JB0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JB0.setText("0");
        JB0.setMaximumSize(new java.awt.Dimension(70, 50));
        JB0.setMinimumSize(new java.awt.Dimension(70, 50));
        JB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB0ActionPerformed(evt);
            }
        });

        jBComa.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBComa.setText(".");
        jBComa.setMaximumSize(new java.awt.Dimension(70, 50));
        jBComa.setMinimumSize(new java.awt.Dimension(70, 50));
        jBComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComaActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBCuadrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JB8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JB9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JBDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JB6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(JB0, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBComa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBCuadrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBComa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Los eventos que ocurren al pulsar los diferentes botones. Si ya números
    escritos con anterioridad, añade el pulsador a lo que ya había en el jTextField1
     */
    private void JB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB0ActionPerformed
        jLabel1.setText("");
        jTextField1.setText(jTextField1.getText() + "0"); //al pulsar el 0. 
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_JB0ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed

        jLabel1.setText("");
        jTextField1.setText(jTextField1.getText() + "1"); //pulsar 1 
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        jTextField1.setText(jTextField1.getText() + "2"); //pulsar 2
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jB2ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        jLabel1.setText("");
        jTextField1.setText(jTextField1.getText() + "3"); //pulsar 3
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
        jLabel1.setText("");
        jTextField1.setText(jTextField1.getText() + "4");//pulsar 4
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_JB4ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
        jLabel1.setText("");
        jTextField1.setText(jTextField1.getText() + "5"); //pulsar 5
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_JB5ActionPerformed

    private void JB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB6ActionPerformed
        jLabel1.setText("");
        jTextField1.setText(jTextField1.getText() + "6"); //pulsar 6
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_JB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        jLabel1.setText("");
        jTextField1.setText(jTextField1.getText() + "7"); //pulsar 7
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jB7ActionPerformed

    private void JB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB8ActionPerformed
        jLabel1.setText("");
        jTextField1.setText(jTextField1.getText() + "8");  //pulsar 8
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_JB8ActionPerformed

    private void JB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB9ActionPerformed
        jLabel1.setText("");
        jTextField1.setText(jTextField1.getText() + "9"); //pulsar 9
        if (jTextField1.getText().length() >= 16) {
            jLabel1.setText("No más de 16 números");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_JB9ActionPerformed
    /*punto decimal, solo deja uno por cada uno de los operandos*/
    private void jBComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComaActionPerformed
        if ((puntoDecimal == 0) || ((puntoDecimal == 1) && (primerNumero == 1))) {
            jTextField1.setText(jTextField1.getText() + ".");  //pulsar el punto decimal
            puntoDecimal = 1;

        } else {
            jLabel1.setText("Error, solo un punto decimal.");
        }
    }//GEN-LAST:event_jBComaActionPerformed

    /*al pulsar los botones de las operaciones aritméticas se almacena en la
    variable numero el String que hay en pantalla y se parsea a Double. Se indica
    cual de los case  corresponde y se deja la pantalla 
    en blanco en espera del siguiente número*/
    private void jBSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSumarActionPerformed

        if (jTextField1.getText().equals("")) {
            jLabel1.setText("Primero escribe los números");
        } else {
            numero = Double.parseDouble(jTextField1.getText());
            calculo = 1;
            textoOperacion = jTextField1.getText() + " + ";
            jLabel1.setText(textoOperacion);
            jTextField1.setText("");
            primerNumero = 1;
        }

    }//GEN-LAST:event_jBSumarActionPerformed

    private void jBRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRestarActionPerformed
        if (jTextField1.getText().equals("")) {
            jLabel1.setText("Primero escribe los números");
        } else {
            numero = Double.parseDouble(jTextField1.getText());
            calculo = 2;
            textoOperacion = jTextField1.getText() + " - ";
            jLabel1.setText(textoOperacion);
            jTextField1.setText("");
            primerNumero = 1;
        }
    }//GEN-LAST:event_jBRestarActionPerformed

    private void jBMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicarActionPerformed
        if (jTextField1.getText().equals("")) {
            jLabel1.setText("Primero escribe los números");
        } else {
            numero = Double.parseDouble(jTextField1.getText());
            calculo = 3;
            textoOperacion = jTextField1.getText() + " * ";
            jLabel1.setText(textoOperacion);
            jTextField1.setText("");
            primerNumero = 1;
        }
    }//GEN-LAST:event_jBMultiplicarActionPerformed

    private void JBDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDividirActionPerformed
        if (jTextField1.getText().equals("")) {
            jLabel1.setText("Primero escribe los números");
        } else {
            numero = Double.parseDouble(jTextField1.getText());
            textoOperacion = jTextField1.getText() + " / ";
            calculo = 4;
            jLabel1.setText(textoOperacion);
            jTextField1.setText("");
            primerNumero = 1;
        }
    }//GEN-LAST:event_JBDividirActionPerformed

    private void jBCuadrado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCuadrado1ActionPerformed
        if (jTextField1.getText().equals("")) {
            jLabel1.setText("Primero escribe los números");
        } else {
            numero = Double.parseDouble(jTextField1.getText());
            textoOperacion = jTextField1.getText();
            calculo = 5;
            jLabel1.setText(textoOperacion);
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jBCuadrado1ActionPerformed
    /*Al pulsar el botón de Eliminar se borra lo que hubiera en el jTextField1*/
    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jBEliminarActionPerformed
    /*El botón de borrar elimina el último carácter escrito. Se pasa lo que hay
    en el jTextField a la veriable numPant (String) y si la longitud de esa 
    variable es mayor que 0 elimina el último caracter utilizando substring*/
    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed

        String numPant = jTextField1.getText().toString();
        if (numPant.length() > 0) {
            numPant = numPant.substring(0, numPant.length() - 1);
            jTextField1.setText(numPant);
        }
    }//GEN-LAST:event_jBBorrarActionPerformed
    /*este botón llama al método operacion() para realizar la operación
    correspondiente que ya estará marcada cuando se pulsó con anterioridad*/
    private void jBIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIgualActionPerformed
        operacion();


    }//GEN-LAST:event_jBIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    private double numero = 0, respuesta;
    private int calculo, puntoDecimal = 0, primerNumero = 0;
    private String textoOperacion;
    ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB0;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JButton JBDividir;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBComa;
    private javax.swing.JButton jBCuadrado1;
    private javax.swing.JButton jBCuadrado2;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBIgual;
    private javax.swing.JButton jBMultiplicar;
    private javax.swing.JButton jBRestar;
    private javax.swing.JButton jBSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
